Rj post comment
lammylol/Flock pull request #36
Opened 2024-10-11 03:55 UTC by ramonjiang

2024-10-11 18:38 UTC, lammylol commented on Flock/Views/Model Views/CommentsView.swift
> +        .onAppear {
I don't think this makes any functional difference, but let's use '.task' instead of .onAppear to be more in sync with all other views.

2024-10-12 16:22 UTC, lammylol requested changes
Yessss love this PR. Can merge once those changes are made!

We will probably need to make some UI adjustments in a separate PR later. But man, this is so solid.

2024-10-12 16:22 UTC, lammylol commented on Flock/Views/Model Views/CommentsView.swift
> +        .navigationTitle(isInSheet ? "" : "Comments")
Can remove navigationTitle now!

2024-10-12 16:22 UTC, lammylol commented on Flock/Views/Model Views/CommentsView.swift
> +        .shadow(radius: 2)
You can delete .padding, .background, .shadow. UI things

2024-10-12 16:22 UTC, lammylol commented on Flock/Views/Model Views/CommentsView.swift
> +                .submitLabel(.send)
imo change to .submitLabel(.return) since .send doesn't mix well with 'post'. Can play around with it later, but let's do .return for now.

2024-10-12 16:22 UTC, lammylol commented on Flock/Views/Model Views/CommentsView.swift
> +                    .padding()
Make font size 16 to match the text font size in the post: .font(.system(size: `16))`
Remove padding to make in line with the left side: // .padding()

2024-10-13 16:15 UTC, ramonjiang commented
made changes as outline above. and tested!

2024-10-13 16:19 UTC, merged