Notifications for comments
lammylol/Flock pull request #52
Opened 2024-10-28 22:51 UTC by ramonjiang

2024-10-29 00:03 UTC, ramonjiang commented
theres some strange issue around permissions and users commenting on posts. i thought it was a firebase rules issue, but now im starting to think somthing needs to be tweaked in auth in code

2024-10-29 21:11 UTC, ramonjiang commented
lets go!!!!!!!!

2024-10-30 19:31 UTC, lammylol requested changes

2024-10-30 19:32 UTC, lammylol commented
Still reviewing because this is so big haha. Just sent out some initial comments.

2024-10-30 19:40 UTC, lammylol commented on Flock/Helpers/PostHelper.swift
> -
Don't touch this part... yet. Toggle pinned stopped working once this code was taken out. 

Test: When you unpin a card, the update is happening in today view, but not profile view. So I don't think pinning can be migrated away from prayer list yet for profile. I will handle this in a separate PR!

2024-10-30 19:41 UTC, lammylol requested changes

2024-10-30 19:41 UTC, lammylol commented on Flock/Helpers/PostHelper.swift
>      }
Don't touch this part... yet. Toggle pinned stopped working once this code was taken out. 

Test: When you unpin a card, the update is happening in today view, but not profile view. So I don't think pinning can be migrated away from prayer list yet for profile. I will handle this in a separate PR!

2024-10-30 19:50 UTC, lammylol commented
I'm not sure if this is the best entire way to do it, but I think we should start a new branch off of Notifications_for_Comments to implement the rest of these requirements: https://www.notion.so/Enable-In-App-Notifications-for-Comments-e6c6d80b692848f2b6cec960e83edbaa?pvs=4.

We can merge that once that's ready into this branch. That way we can test and make sure things are all working before integrating into Main. Since we don't have feature flags yet, we can't really separate out things from Main vs. what we ship to TestFlight if we find some issues that need further research.

2024-10-30 20:01 UTC, lammylol commented on Flock/Views/Model Views/Comment Model Views/CommentsView.swift
> +                        Divider()
Update: No action needed - I am adding a separate UI Branch to this branch!

2024-10-30 20:01 UTC, lammylol commented on Flock.xcodeproj/project.pbxproj
Update: No action needed - I am adding a separate UI Branch to this branch!

2024-10-30 20:17 UTC, lammylol requested changes

2024-10-30 20:17 UTC, lammylol commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
What is the onChange needed for? IMO seems unnecessary and I think we should find a workaround. NotificationSheet shouldn't require any additional tasks different from either our Comments, Feed, Post views, etc.

2024-10-30 20:17 UTC, lammylol commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
Can we have this sit as a task within the notification sheet itself? Also wonder if we can find a workaround for this. I know it has to do with the .init, but wondering if we can remove this extra task or it may get confusing in the future. Ideally the userHolder.person.userID gets set by the environment and shouldn't need to update anything.

2024-11-01 00:45 UTC, ramonjiang commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
you're right. good catch. onAppear is sufficent

2024-11-01 00:48 UTC, ramonjiang commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
yep. good call again. moved to notfication sheet

2024-11-01 00:49 UTC, ramonjiang commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
done

2024-11-01 00:49 UTC, ramonjiang commented on Flock/Views/Main Views/Today View/TodayView.swift
> +            }
done

2024-11-01 00:49 UTC, ramonjiang commented on Flock/Views/Model Views/Comment Model Views/CommentViewModel.swift
> +            let post = try await postOperationsService.getPost(prayerRequest: tempPost, user: person)
done

2024-11-01 00:49 UTC, ramonjiang commented on Flock/Views/Model Views/Comment Model Views/CommentsView.swift
> +        try? await viewModel.addComment(postID: postID, text: newCommentText)
done

2024-11-01 00:49 UTC, ramonjiang commented on Flock/Views/Model Views/NotificationViewModel.swift
> +class NotificationViewModel: ObservableObject {
done

2024-11-02 18:32 UTC, ramonjiang commented
@lammylol made all changes as discussed here: https://www.notion.so/7a20c472b3bc4b50b79d57fdfdf22f73?v=03d735b576d64ca184e3daf0b4818ec8&p=13150a0c1d228072ba9bcc86efeb66e7&pm=s

2024-11-03 00:54 UTC, ramonjiang commented
@lammylol  LEGGO

2024-11-04 06:10 UTC, lammylol requested changes
Last thing is to remove all the print statements and get logging in after we merge into main. Can be a follow up.

2024-11-04 06:10 UTC, lammylol commented on Flock/Views/Model Views/NotificationViewModel.swift
> +        listener?.remove()  // Clean up listener when ViewModel is deallocated
Is the deinit referenced anywhere? I would suggest implementing it in signOut similar to how friendsListener turns off. If not, the listener will keep running which we don't want to happen.

2024-11-04 06:35 UTC, ramonjiang commented on Flock/Views/Main Views/Notifications/NotificationSheet.swift
> +        do {
makes sense

2024-11-04 06:47 UTC, ramonjiang commented on Flock/Views/Model Views/NotificationViewModel.swift
> +        listener?.remove()  // Clean up listener when ViewModel is deallocated
not referenced anywhere. I can implement in ProfileSettingsView signOut w/ friendsListener

2024-11-04 06:49 UTC, ramonjiang commented
> Last thing is to remove all the print statements and get logging in after we merge into main. Can be a follow up.

Ya. i can make a clean up branch after merge

2024-11-05 05:00 UTC, lammylol approved these changes

2024-11-05 05:01 UTC, merged